# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: qr-code-maker

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.qrMaker
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: qrcode
          method: post
          cors: true
          integration: lambda
